2025-05-26 22:54:38,134 ERROR: Exception on /lesson/1 [GET] [in C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\routes.py", line 139, in lesson_detail
    return render_template('lesson_detail.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\base.html", line 126, in top-level template code
    {% block content %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 254, in block 'content'
    {% set submission = current_user.submissions.filter_by(test_id=test.id).first() if not current_user.is_teacher else None %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.local_auth.User object' has no attribute 'submissions'
2025-05-26 22:54:38,169 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:188]
Traceback (most recent call last):
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\routes.py", line 139, in lesson_detail
    return render_template('lesson_detail.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\base.html", line 126, in top-level template code
    {% block content %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 254, in block 'content'
    {% set submission = current_user.submissions.filter_by(test_id=test.id).first() if not current_user.is_teacher else None %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.local_auth.User object' has no attribute 'submissions'
2025-05-26 22:54:55,836 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:54:55,836 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:54:55,844 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:54:55,846 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:54:55,860 INFO: [2025-05-26 22:54:55] User 5: view_student_dashboard [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:04,661 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:04,662 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:04,690 INFO: [2025-05-26 22:55:04] User 5: view_student_dashboard [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:05,763 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:05,763 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:06,506 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:06,506 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:07,607 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:07,607 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
