2025-05-26 22:55:07,624 ERROR: Exception on /lesson/1 [GET] [in C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\routes.py", line 139, in lesson_detail
    return render_template('lesson_detail.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\base.html", line 126, in top-level template code
    {% block content %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 254, in block 'content'
    {% set submission = current_user.submissions.filter_by(test_id=test.id).first() if not current_user.is_teacher else None %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.local_auth.User object' has no attribute 'submissions'
2025-05-26 22:55:07,648 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:188]
Traceback (most recent call last):
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\routes.py", line 139, in lesson_detail
    return render_template('lesson_detail.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\base.html", line 126, in top-level template code
    {% block content %}
  File "C:\Users\ENVY\Downloads\sewing_lms_ready\app\templates\lesson_detail.html", line 254, in block 'content'
    {% set submission = current_user.submissions.filter_by(test_id=test.id).first() if not current_user.is_teacher else None %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.local_auth.User object' has no attribute 'submissions'
2025-05-26 22:55:08,823 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:08,823 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:08,829 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:08,830 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:08,843 INFO: [2025-05-26 22:55:08] User 5: view_student_dashboard [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:09,996 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:09,998 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:10,030 INFO: [2025-05-26 22:55:10] User 5: start_test_2 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:12,448 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:12,449 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:12,461 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:12,462 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:12,484 INFO: [2025-05-26 22:55:12] User 5: view_student_dashboard [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:14,161 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:14,162 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:15,631 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:15,631 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:15,643 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:15,644 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:15,662 INFO: [2025-05-26 22:55:15] User 5: view_student_dashboard [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:17,660 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:17,661 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:17,688 INFO: [2025-05-26 22:55:17] User 5: view_my_results [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
2025-05-26 22:55:21,072 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:21,073 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:21,083 INFO: Загрузка пользователя с ID: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:61]
2025-05-26 22:55:21,083 INFO: Пользователь найден в сессии: 5 [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\__init__.py:65]
2025-05-26 22:55:21,109 INFO: [2025-05-26 22:55:21] User 5: view_student_dashboard [in C:\Users\ENVY\Downloads\sewing_lms_ready\app\utils\__init__.py:35]
